.TH dispatcher 1 "April 2021" Linux "User Manuals"


.SH NAME
    dispatcher

.SH SYNOPSIS
    ./out [-b] -l <num>

.SH OPTIONS
    -b toggles line buffering
    -l Set maximum number of listeners (1 - 100)

.SH DESCRIPTION
dispatcher - Sends text from stdin to connected clients.
Requires port number to be set on environment variable RELAY

.SH AUTHOR
    jkaten (jereack@gmail.com), jsanchez, mmiano

.SH SEE ALSO
    hangman, mastermind, bottles, guess, ws, zerg, battleship, polynomial, etc..
