.TH listener 1 "April 2021" Linux "User Manuals"


.SH NAME
    listener

.SH SYNOPSIS
    ./listener

.SH OPTIONS
    None

.SH DESCRIPTION
listener - Recieved text from server and prints to stdout.
Requires port number to be set on environment variable RELAY

.SH AUTHOR
    jkaten (jereack@gmail.com), jsanchez, mmiano

.SH SEE ALSO
    hangman, mastermind, bottles, guess, ws, zerg, battleship, polynomial, etc..
