.TH signaler 1 "April 2021" Linux "User Manuals"


.SH NAME
    signaler

.SH SYNOPSIS
    ./signaler [-r] -s <num> -e <num> -t <num>

.SH OPTIONS
    -s set starting number (greater than 0)
    -r start in reverse mode (greater than 0)
    -e specify end number
    -t specify sleep time (positive integer value)

.SH DESCRIPTION
signaler - prints increasing prime numbers every second.

.SH AUTHOR
    Jerimiah Katen (jereack@gmail.com)

.SH SEE ALSO
    hangman, mastermind, bottles, guess, ws, zerg, battleship, polynomial, etc..
