.TH fibonacci 1 "April 2021" Linux "User Manuals"

.SH NAME
    fibonacci

.SH SYNOPSIS
    ./fibonacci [-o] <num(0-300)>

.SH OPTIONS
    -o - print fibonacci number in octal

.SH DESCRIPTION
fibonacci - Prints Nth fibonacci number in hex

.SH AUTHOR
    jkaten (jereack@gmail.com), emacgr (iondiomac@gmail.com)

.SH SEE ALSO
    hangman, mastermind, bottles, guess, ws, zerg, battleship, polynomial, etc..
