.TH bank_of_nerds 1 "February 2021" Linux "User Manuals"


.SH NAME
    bank_of_nerds.py

.SH SYNOPSIS
    ./bank_of_nerds.py [--secret string]

.SH OPTIONS
--secret - Checks if string matches a secret.

.SH DESCRIPTION
Bank of Nerds is a basic banking system. The bank includes accounts, customers, transactions and a menu interface. Customers can have multiple accounts. The types of accounts a customer can have are; savings, checking, 401(k) and Money Market Fund.

.SH AUTHOR
    Jerimiah Katen

.SH SEE ALSO
    hangman, mastermind, bottles, guess, ws, zerg, battleship, polynomial, etc..
