all:
	gcc -Wall -Wextra -Wpedantic -Wvla -Wwrite-strings -Wfloat-equal -o hangman hangman.c

debug:
	gcc -g -Wall -Wextra -Wpedantic -Wvla -Wwrite-strings -Wfloat-equal -o hangman hangman.c

clean:
	rm hangman
